#!/usr/bin/python

import re
import shutil

struct_start = re.compile("struct ([a-z_]+)_args {")
struct_end = re.compile("};")
function_name = re.compile(".*Autogenerate:[ \t]*([a-z_]+).*")

infile = open("../../include/kern/sfs.h", "rb")
template = open("sfs_jentries_template.c", "rb")
outfile = open("sfs_jentries.c", "wb")

def parse_structs(file_obj):
	struct = None
	structs = {}
	for line in infile:
		# Start of struct
		if struct_start.match(line) and "_args" in line and "ignore" not in line:
			struct = struct_start.search(line).group(1)
			structs[struct] = []
		# End of struct
		elif struct_end.match(line) and struct:
			struct = None
		# Content of struct
		elif struct and "\t" in line and "ignore" not in line:
			line = re.sub("[;\t\n]", "", line)
			tokens = line.split(" ")
			if "*" in line:
				tokens = line.split("*")
				tokens[0] += "*"
			structs[struct].append(tokens)
	return structs

def main():
	global infile
	global template
	structs = parse_structs(infile)
	write("/* This is an autogenerated file. Modify sfs_jentries_template.c instead */\n\n")
	for line in template:
		if function_name.match(line):
			to_run = "autogenerate_" + function_name.search(line).group(1)
			globals()[to_run](structs)
		else:
			write(line)

def write(line):
	#print line
	global outfile
	outfile.write(line)

def autogenerate_cases(structs):
	for struct in structs:
		fmt = {
			"struct_name": struct,
			"struct_name_upper": struct.upper(),
		}
		write("""		case %(struct_name_upper)s:
			reclen = sizeof(struct %(struct_name)s_args);
			break;\n""" % fmt)

def autogenerate_print(structs):
	for struct in structs:
		print_format = []
		print_args = []
		for ctype, name in structs[struct]:
			if "void" in ctype:
				print_format.append("%s=%%p" % name)
			else:
				print_format.append("%s=%%d" % name)
			print_args.append("((struct %s_args*)recptr)->%s" % (struct, name))
		fmt = {
			"struct_name_upper": struct.upper(),
			"print_format": ", ".join(print_format),
			"print_args": ",\n\t\t\t\t".join(print_args)
		}
		write("""		case %(struct_name_upper)s:
			kprintf("%(struct_name_upper)s(%(print_format)s)",
				%(print_args)s);
			break;\n""" % fmt)

def autogenerate_functions(structs):
	for struct in structs:
		initializations = []
		entry_args = []
		for ctype, name in structs[struct]:
			if "code" in name:
				continue
			if name == "id":
				initializations.append("record->id = curproc->pid;")
				continue
			entry_args.append("%s %s" % (ctype, name))
			initializations.append("record->%s = %s;" % (name, name))

		fmt = {
			"struct_name": struct,
			"struct_name_upper": struct.upper(),
			"entry_args": ", ".join(entry_args),
			"initializations": "\n\t".join(initializations)
		}

		write("""void *jentry_%(struct_name)s(%(entry_args)s)
{
	struct %(struct_name)s_args *record;

	record = kmalloc(sizeof(struct %(struct_name)s_args));
	record->code = %(struct_name_upper)s;
	%(initializations)s

	return (void *)record;
}\n\n""" % fmt)

if __name__ == "__main__":
	print "Generating..."
	main()
	global infile
	global outfile
	global template
	infile.close()
	outfile.close()
	template.close()
	print "Done."